# Generated by Django 5.0.7 on 2024-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishId', models.PositiveBigIntegerField(unique=True)),
                ('dishName', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(blank=True, max_length=511, null=True)),
                ('isPublished', models.BooleanField(default=False)),
            ],
        ),
    ]
